spring:
  profiles:
    active : dev
  datasource:
      username: root
      password: 1172176452
      url: jdbc:mysql://127.0.0.1:3306/redpack?serverTimezone=GMT%2B8&ucseSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
      driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  mvc:
    throw-exception-if-no-handler-found : true
    resources:
      add-mappings : false

  #系统配置
  app:
    config:
      persist : true
      crash-recovery-inteval : 300


